# NumPy

<span style="color: blue">**NumPy** is a Python library that provides a multidimensional array object</span> and many associated operations.

Numpy arrays are one of the most powerful tools for scientific Python. They are extremely optimized and allow for super-efficient calculations.

An array is like a table, just that it can have as many rows, columns as you want! It can also be 3D, 4D or any-D you want!

Now you can see that it makes a lot of sense to load microscopy images as Numpy arrays. No matter if they have few channels, several times points, Z-stack etc.., as long as you can load them in your RAM on your computer, Numpy arrays can handle it!

https://numpy.org/

In [1]:
# To access the Numpy library we need to import it
import numpy as np # it is custom to give it the 'np' name

# There are many Numpy functions, here are a few to create new arrays from scratch
arr1 = np.zeros((2,2))
arr2 = np.ones(10)
arr3 = np.arange(1,10,2)
arr4 = np.random.normal(0,2,10)

# Use the print function to display the arrays!
print(arr3)

[1 3 5 7 9]


Numpy arrays have a lot of built in functions that are very useful! All those functions are usually also found in the base Numpy library.

In [2]:
print(arr4.mean())
print(np.mean(arr4))
print(arr4.std())
print(arr3.max())
print(arr3.sum())

# shape is very useful to know the shape of an array!
print(arr1.shape) 

0.8052791910835122
0.8052791910835122
2.1105303315141053
9
25
(2, 2)


You can also do standard mathematical operations wtih Numpy arrays

<span style="color: blue"> we can create the array with randint numpy function:
    random.randint(low, high, size)
</span>


In [3]:
# we can create the array with randint numpy fonction:


a1 = np.random.randint(10,20, 5) # random.randint(low, high, size)
a2 = np.random.randint(10,30, 5)
diff = a1 - a2
print(diff)
print(diff * -1)
print(diff ** 2) # in Python ** is the equivalent to ^ for elevating to nth power

[-13  -4  -1  -6  -5]
[13  4  1  6  5]
[169  16   1  36  25]


Numpy arrays have a lot of similar properties to Python lists. You can slice them and modify specific elements.

In [4]:
matrix1 = np.zeros((5,5), dtype=int) # most numpy functions have a dtype param that allows you to choose the data type (int, float, 8bit, 16 bit etc..)
matrix1[1:4, 1:4] = 1
print(matrix1, '\n') # this \n is just an HTML command for a new line. We use it just to create an emtpy line between the print output

matrix2 = np.random.randint(1, 10, size=(5,5))
print(matrix2, '\n')

multiplied = matrix1 * matrix2
print(multiplied, '\n')

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]] 

[[7 5 6 9 2]
 [2 2 8 2 2]
 [5 2 9 9 5]
 [8 2 9 9 7]
 [1 2 7 9 3]] 

[[0 0 0 0 0]
 [0 2 8 2 0]
 [0 2 9 9 0]
 [0 2 9 9 0]
 [0 0 0 0 0]] 

